-- Giải đấu (competitions) feature.
--
-- Club members are rows in public.users; opponent players only exist as free
-- text on lineups and match events, so every "player" column comes in a pair:
-- a nullable user_id for our own players and a nullable name for everybody else.
--
-- Apply with the Supabase SQL editor (or `supabase db push`), then run
-- `npm run type:generate` to refresh database.types.ts.

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

-- security definer so the check works even when RLS hides other users' rows.
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'ADMIN'
  );
$$;

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

alter table public.users
  add column if not exists shirt_number smallint;

create table if not exists public.competitions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  season text,
  legs smallint not null default 1,
  team_count smallint,
  start_date date,
  end_date date,
  venue text,
  organizer text,
  status text not null default 'ongoing'
    check (status in ('upcoming', 'ongoing', 'finished'))
);

create table if not exists public.competition_teams (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  competition_id bigint not null references public.competitions (id) on delete cascade,
  name text not null,
  abbr text,
  is_own_team boolean not null default false,
  unique (competition_id, name)
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  competition_id bigint not null references public.competitions (id) on delete cascade,
  round smallint,
  match_date date not null,
  kickoff_time time,
  venue text,
  referee text,
  home_team_id bigint not null references public.competition_teams (id) on delete cascade,
  away_team_id bigint not null references public.competition_teams (id) on delete cascade,
  home_score smallint,
  away_score smallint,
  status text not null default 'finished'
    check (status in ('scheduled', 'live', 'finished')),
  check (home_team_id <> away_team_id)
);

create table if not exists public.match_lineups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  match_id bigint not null references public.matches (id) on delete cascade,
  competition_team_id bigint not null references public.competition_teams (id) on delete cascade,
  user_id uuid references public.users (id) on delete set null,
  player_name text,
  shirt_number smallint,
  position text,
  is_starter boolean not null default true,
  check (user_id is not null or player_name is not null)
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  match_id bigint not null references public.matches (id) on delete cascade,
  competition_team_id bigint not null references public.competition_teams (id) on delete cascade,
  minute smallint,
  type text not null default 'goal'
    check (type in ('goal', 'own_goal', 'substitution', 'yellow_card', 'red_card')),
  player_user_id uuid references public.users (id) on delete set null,
  player_name text,
  assist_user_id uuid references public.users (id) on delete set null,
  assist_name text,
  note text,
  check (player_user_id is not null or player_name is not null)
);

create table if not exists public.motm_votes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  match_id bigint not null references public.matches (id) on delete cascade,
  voter_id uuid not null default auth.uid() references public.users (id) on delete cascade,
  player_user_id uuid references public.users (id) on delete cascade,
  player_name text,
  unique (match_id, voter_id),
  check (player_user_id is not null or player_name is not null)
);

create index if not exists competition_teams_competition_id_idx on public.competition_teams (competition_id);
create index if not exists matches_competition_id_idx on public.matches (competition_id);
create index if not exists match_lineups_match_id_idx on public.match_lineups (match_id);
create index if not exists match_lineups_user_id_idx on public.match_lineups (user_id);
create index if not exists match_events_match_id_idx on public.match_events (match_id);
create index if not exists match_events_player_user_id_idx on public.match_events (player_user_id);
create index if not exists match_events_assist_user_id_idx on public.match_events (assist_user_id);
create index if not exists motm_votes_match_id_idx on public.motm_votes (match_id);

-- ---------------------------------------------------------------------------
-- Row level security: everybody signed in can read, only admins can write.
-- ---------------------------------------------------------------------------

-- Supabase grants these by default privilege; repeat it so the migration also
-- works on projects where the default privileges were changed.
grant select, insert, update, delete on
  public.competitions,
  public.competition_teams,
  public.matches,
  public.match_lineups,
  public.match_events,
  public.motm_votes
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

alter table public.competitions enable row level security;
alter table public.competition_teams enable row level security;
alter table public.matches enable row level security;
alter table public.match_lineups enable row level security;
alter table public.match_events enable row level security;
alter table public.motm_votes enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'competitions', 'competition_teams', 'matches', 'match_lineups', 'match_events'
  ] loop
    execute format('drop policy if exists %I on public.%I', t || '_read', t);
    execute format('drop policy if exists %I on public.%I', t || '_write', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (true)',
      t || '_read', t
    );
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      t || '_write', t
    );
  end loop;
end;
$$;

-- Voting is open to every signed in member, but only for their own vote.
drop policy if exists motm_votes_read on public.motm_votes;
create policy motm_votes_read on public.motm_votes
  for select to authenticated using (true);

drop policy if exists motm_votes_write on public.motm_votes;
create policy motm_votes_write on public.motm_votes
  for all to authenticated
  using (voter_id = auth.uid())
  with check (voter_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Reporting functions
--
-- Every body wraps its select in a subquery so that column references stay
-- unambiguous against the RETURNS TABLE output parameters.
-- ---------------------------------------------------------------------------

create or replace function public.get_competition_standings(p_competition_id bigint)
returns table (
  team_id bigint,
  team_name text,
  abbr text,
  is_own_team boolean,
  played bigint,
  won bigint,
  drawn bigint,
  lost bigint,
  goals_for bigint,
  goals_against bigint,
  goal_diff bigint,
  points bigint
)
language sql
stable
as $$
  with results as (
    select m.home_team_id as team, m.home_score as scored, m.away_score as conceded
    from public.matches m
    where m.competition_id = p_competition_id
      and m.status = 'finished'
      and m.home_score is not null
      and m.away_score is not null
    union all
    select m.away_team_id, m.away_score, m.home_score
    from public.matches m
    where m.competition_id = p_competition_id
      and m.status = 'finished'
      and m.home_score is not null
      and m.away_score is not null
  ),
  totals as (
    select
      t.id as team,
      t.name as label,
      t.abbr as short,
      t.is_own_team as own,
      count(r.team)::bigint as p,
      (count(*) filter (where r.scored > r.conceded))::bigint as w,
      (count(*) filter (where r.scored = r.conceded))::bigint as d,
      (count(*) filter (where r.scored < r.conceded))::bigint as l,
      coalesce(sum(r.scored), 0)::bigint as gf,
      coalesce(sum(r.conceded), 0)::bigint as ga
    from public.competition_teams t
    left join results r on r.team = t.id
    where t.competition_id = p_competition_id
    group by t.id, t.name, t.abbr, t.is_own_team
  )
  select
    s.team,
    s.label,
    s.short,
    s.own,
    s.p,
    s.w,
    s.d,
    s.l,
    s.gf,
    s.ga,
    s.gf - s.ga,
    s.w * 3 + s.d
  from totals s
  order by s.w * 3 + s.d desc, s.gf - s.ga desc, s.gf desc, s.label;
$$;

create or replace function public.get_competition_scorers(p_competition_id bigint)
returns table (
  player_key text,
  player_name text,
  user_id uuid,
  team_name text,
  goals bigint,
  assists bigint
)
language sql
stable
as $$
  with contributions as (
    select e.competition_team_id as team, e.player_user_id as uid, e.player_name as label, 1 as g, 0 as a
    from public.match_events e
    join public.matches m on m.id = e.match_id
    where m.competition_id = p_competition_id and e.type = 'goal'
    union all
    select e.competition_team_id, e.assist_user_id, e.assist_name, 0, 1
    from public.match_events e
    join public.matches m on m.id = e.match_id
    where m.competition_id = p_competition_id
      and e.type = 'goal'
      and (e.assist_user_id is not null or e.assist_name is not null)
  ),
  totals as (
    select
      coalesce(c.uid::text, c.label) as key,
      coalesce(
        nullif(trim(concat_ws(' ', u.first_name, u.last_name)), ''),
        c.label
      ) as label,
      c.uid as uid,
      t.name as team,
      sum(c.g)::bigint as g,
      sum(c.a)::bigint as a
    from contributions c
    left join public.users u on u.id = c.uid
    left join public.competition_teams t on t.id = c.team
    group by 1, 2, 3, 4
  )
  select s.key, s.label, s.uid, s.team, s.g, s.a
  from totals s
  where s.key is not null
  order by s.g desc, s.a desc, s.label;
$$;

create or replace function public.get_squad_stats()
returns table (
  user_id uuid,
  first_name text,
  last_name text,
  player_position text,
  shirt_number smallint,
  apps bigint,
  goals bigint,
  assists bigint
)
language sql
stable
as $$
  select s.id, s.first, s.last, s.pos, s.shirt, s.apps, s.goals, s.assists
  from (
    select
      u.id as id,
      u.first_name as first,
      u.last_name as last,
      u.position as pos,
      u.shirt_number as shirt,
      (
        select count(distinct l.match_id)
        from public.match_lineups l
        where l.user_id = u.id
      )::bigint as apps,
      (
        select count(*)
        from public.match_events e
        where e.player_user_id = u.id and e.type = 'goal'
      )::bigint as goals,
      (
        select count(*)
        from public.match_events e
        where e.assist_user_id = u.id and e.type = 'goal'
      )::bigint as assists
    from public.users u
  ) s
  order by s.shirt nulls last, s.first, s.last;
$$;

create or replace function public.get_player_competition_stats(p_user_id uuid)
returns table (
  competition_id bigint,
  competition_name text,
  apps bigint,
  goals bigint,
  assists bigint
)
language sql
stable
as $$
  select s.id, s.label, s.apps, s.goals, s.assists
  from (
    select
      c.id as id,
      c.name as label,
      c.start_date as started,
      (
        select count(distinct l.match_id)
        from public.match_lineups l
        join public.matches m on m.id = l.match_id
        where l.user_id = p_user_id and m.competition_id = c.id
      )::bigint as apps,
      (
        select count(*)
        from public.match_events e
        join public.matches m on m.id = e.match_id
        where e.player_user_id = p_user_id and e.type = 'goal' and m.competition_id = c.id
      )::bigint as goals,
      (
        select count(*)
        from public.match_events e
        join public.matches m on m.id = e.match_id
        where e.assist_user_id = p_user_id and e.type = 'goal' and m.competition_id = c.id
      )::bigint as assists
    from public.competitions c
  ) s
  where s.apps > 0 or s.goals > 0 or s.assists > 0
  order by s.started desc nulls last, s.label;
$$; 
